# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Francesco Greppi
email: francesco.greppi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hello, welcome to my blog! Thank you for visiting my little space on the web. My blog is about Javascript, JS frameworks, development methodologies and best practices. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://francescogreppi.github.io/" # the base hostname & protocol for your site
github_username: francescogreppi

# Build settings
markdown: kramdown
