# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I don't know JS
email: francesco.greppi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  **I don't know JS** is my personal approach to the discovery of Javascript. I'll write this blog to explain to myself in a concise way all the concepts that are at the core of Javascript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: francescogreppi

# Build settings
markdown: kramdown
