# Site settings
title: Francesco Greppi
email: francesco.greppi@gmail.com
description: Hello welcome to my blog
baseurl: ""
url: "https://francescogreppi.github.io/"

author:
  name     : 'Francesco Greppi'
  email    : francesco.greppi@gmail.com
  url      : https://francescogreppi.github.io/

github: https://github.com/francescogreppi
disqus_shortname: "francescogreppi"
google_analytics: UA-76737439-1

paginate: 6
comments: false
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/

# Gems
gems: [jekyll-paginate]
